#electricprotons.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: regular-
spec:
  entrypoint: regular
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: nfs-1
  templates:
  - name: regular
    script:
      image: docker.io/dacb1997/tesisdeployers:regular
      command: [sh]
      source: |
        bash go-regular-pr-1.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "First Ready"
        mv  regular/DAT* /mnt/vol/
        bash go-regular-pr-2.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Second Ready"
        mv  regular/DAT* /mnt/vol/
	bash go-regular-pr-3.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Third Ready Ready"
        mv  regular/DAT* /mnt/vol/
        echo ls -l /mnt/vol
        ls -l /mnt/vol
      volumeMounts:
      - name: task-pv-storage
        mountPath: /mnt/vol
