#electricprotons.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: magnetic-
spec:
  entrypoint: magnetic
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: nfs-1
  templates:
  - name: magnetic
    script:
      image: docker.io/dacb1997/tesisdeployers:magnetic
      command: [sh]
      source: |
        bash go-magnetic-pr-1.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "First Ready"
        mv  magnetic/DAT* /mnt/vol/
        bash go-magnetic-pr-2.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Second Ready"
        mv  magnetic/DAT* /mnt/vol/
	bash go-magnetic-pr-3.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Third Ready Ready"
        mv  magnetic/DAT* /mnt/vol/
        echo ls -l /mnt/vol
        ls -l /mnt/vol
      volumeMounts:
      - name: task-pv-storage
        mountPath: /mnt/vol
