#magneticprotons.yaml
#launches the simulations for nucleus
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: magnetic-
spec:
  entrypoint: magnetic
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: nfs-1
  templates:
  - name: magnetic
    script:
      image: docker.io/dacb1997/tesisdeployers:magnetic
      command: [sh]
      source: |
        bash go-magnetic-all-01.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "First Set Ready"
        mv  magnetic/DAT* /mnt/vol/
        bash go-magnetic-all-02.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Second Set Ready"
        mv  magnetic/DAT* /mnt/vol/
	bash go-magneticic-all-03.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Third Set Ready"
        mv  magnetic/DAT* /mnt/vol/
	bash magnetic-all-04.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Fourth Set Ready"
        mv  magnetic/DAT* /mnt/vol/
        bash go-magnetic-all-05.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Fifth Set Ready"
        mv  magnetic/DAT* /mnt/vol/
	bash go-magnetic-all-06.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Sixth Set Ready"
        mv  magnetic/DAT* /mnt/vol/
        echo ls -l /mnt/vol
        ls -l /mnt/vol
      volumeMounts:
      - name: task-pv-storage
        mountPath: /mnt/vol
