#electricprotons2.yaml
#Deploys prtons simulations 4 5 and 6
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: electric-
spec:
  entrypoint: electric
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: nfs-1
  templates:
  - name: electric
    script:
      image: docker.io/dacb1997/tesisdeployers:electric
      command: [sh]
      source: |
        bash go-electric-pr-4.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Fourth Ready"
        mv  electric/DAT* /mnt/vol/
        bash go-electric-pr-5.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Fifth Ready"
        mv  electric/DAT* /mnt/vol/
	bash go-electric-pr-6.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Sixth Ready"
        mv  electric/DAT* /mnt/vol/
        echo ls -l /mnt/vol
        ls -l /mnt/vol
      volumeMounts:
      - name: task-pv-storage
        mountPath: /mnt/vol