#Si se ultiliza un nombre diferente para el disco, es necesario hacer el cambio en pdName
# Se podria cambiar el nombre del servidor, eso debe reflejarse en '002-nfs-server-service.yaml'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-1
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server-1
  template:
    metadata:
      labels:
        role: nfs-server-1
    spec:
      containers:
      - name: nfs-server-1
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mypvc
      volumes:
        - name: mypvc
          gcePersistentDisk:
            pdName: gce-nfs-disk-1
            fsType: ext4
