# pv-pod.yaml
#Crea un contenedor busybox para acceder a nuestros archivos guardados, si se utilizo un nombre diferente de claim de volumen persistente esto debe reflejarse aqui
apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: nfs-1
  containers:
    - name: pv-container
      image: busybox
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - mountPath: /mnt/data
          name: task-pv-storage
