#electricprotons.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: electric-
spec:
  entrypoint: electric
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: nfs-1
  templates:
  - name: electric
    script:
      image: docker.io/dacb1997/tesisdeployers:electric
      command: [sh]
      source: |
        bash go-electric-all-01.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "First Set Ready"
        mv  electric/DAT* /mnt/vol/
        bash go-electric-all-02.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Second Set Ready"
        mv  electric/DAT* /mnt/vol/
	bash go-electric-all-03.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Third Set Ready"
        mv  electric/DAT* /mnt/vol/
	bash go-electric-all-04.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Fourth Set Ready"
        mv  electric/DAT* /mnt/vol/
        bash go-electric-all-05.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Fifth Set Ready"
        mv  electric/DAT* /mnt/vol/
	bash go-electric-all-06.sh 
        while screen -list | grep -q "There are screens on"
        do
        sleep 3600
        screen -list 
        done 
        echo "Sixth Set Ready"
        mv  electric/DAT* /mnt/vol/
        echo ls -l /mnt/vol
        ls -l /mnt/vol
      volumeMounts:
      - name: task-pv-storage
        mountPath: /mnt/vol
